# Generated by Django 4.0.1 on 2022-01-05 13:28

from django.db import migrations, models
import quran.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='سر متن')),
                ('description', models.TextField(max_length=1500, verbose_name='درباره ما')),
            ],
            options={
                'verbose_name': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='سر متن')),
                ('description', models.TextField(max_length=1500, verbose_name='ارتباط با ما')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
            },
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('number', models.IntegerField(verbose_name='شماره تلفن')),
                ('view', models.TextField(max_length=2500, verbose_name='نظر و انتقادات')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=quran.models.user_directory_path, verbose_name='لوگو')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=quran.models.user_directory_path, verbose_name='لوگو')),
                ('title', models.CharField(max_length=500, verbose_name='آیه')),
                ('description', models.TextField(max_length=1500, verbose_name='معنی')),
                ('text', models.CharField(max_length=50, verbose_name='نام سوره، شماره آیه')),
                ('photo', models.ImageField(upload_to=quran.models.user_directory_path, verbose_name='تصویر')),
                ('title1', models.CharField(max_length=500, verbose_name='آیه')),
                ('description1', models.TextField(max_length=1500, verbose_name='معنی')),
                ('text1', models.CharField(max_length=50, verbose_name='نام سوره، شماره آیه')),
            ],
            options={
                'verbose_name': 'صفحه اصلی-هدر',
            },
        ),
    ]
