# Generated by Django 4.0.1 on 2022-01-22 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import quran.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.IntegerField(default=0)),
                ('joz', models.CharField(max_length=50, verbose_name='جز')),
                ('sura', models.CharField(max_length=50, verbose_name='سوره')),
                ('ayaNumber', models.CharField(max_length=50, verbose_name='آیه')),
                ('text', models.TextField(max_length=1500, verbose_name='متن')),
                ('translation', models.TextField(max_length=1500, verbose_name='ترجمه')),
                ('location', models.CharField(max_length=50, null=True, verbose_name='مکان نزول')),
                ('tafsir', models.TextField(max_length=1500, null=True, verbose_name='تفسیر')),
                ('relatedAya', models.CharField(max_length=150, null=True, verbose_name='آیات مرتبط')),
                ('point', models.CharField(max_length=50, null=True, verbose_name='هدف آیه')),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'آیه ها',
            },
        ),
        migrations.CreateModel(
            name='Contact_footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('number', models.IntegerField(verbose_name='شماره تلفن')),
                ('suggestion', models.TextField(max_length=2500, verbose_name='نظر و انتقادات')),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'پیام ها_پاورقی',
            },
        ),
        migrations.CreateModel(
            name='Hadis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imam', models.CharField(max_length=50, verbose_name='امام')),
                ('text', models.TextField(max_length=1500, verbose_name='متن')),
                ('book', models.CharField(max_length=50, verbose_name='کتاب')),
                ('pageNumber', models.CharField(max_length=50, verbose_name='صفحه')),
            ],
            options={
                'verbose_name': 'حدیث ها',
            },
        ),
        migrations.CreateModel(
            name='Messages_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('username', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('phonenumber', models.IntegerField(verbose_name='شماره موبایل')),
                ('email', models.CharField(max_length=150, verbose_name='پست الکترونیک')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
                ('message', models.CharField(max_length=5000, verbose_name='پیغام')),
            ],
            options={
                'verbose_name': 'پیام ها_ارتباط',
            },
        ),
        migrations.CreateModel(
            name='Settings_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(upload_to=quran.models.user_directory_path, verbose_name='لوگو')),
                ('header_title', models.CharField(max_length=500, verbose_name='آیه')),
                ('header_description', models.TextField(max_length=1500, verbose_name='معنی')),
                ('header_text', models.CharField(max_length=50, verbose_name='نام سوره، شماره آیه')),
                ('header_photo', models.ImageField(upload_to=quran.models.user_directory_path, verbose_name='تصویر')),
                ('header_title1', models.CharField(max_length=500, verbose_name='آیه')),
                ('header_description1', models.TextField(max_length=1500, verbose_name='معنی')),
                ('header_text1', models.CharField(max_length=50, verbose_name='نام سوره، شماره آیه')),
                ('about_title', models.CharField(max_length=500, verbose_name='سر متن')),
                ('about_description', models.TextField(max_length=1500, verbose_name='درباره ما')),
                ('donateCard_bankName', models.CharField(max_length=50, verbose_name='اسم بانک')),
                ('donateCard_cardNumber', models.IntegerField(verbose_name='شماره کارت')),
                ('donateCard_ownerName', models.CharField(max_length=50, verbose_name='نام')),
                ('contact_title', models.CharField(max_length=500, verbose_name='سر متن')),
                ('contact_description', models.TextField(max_length=1500, verbose_name='ارتباط با ما')),
                ('footer_logo', models.ImageField(upload_to=quran.models.user_directory_path, verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'اصلی',
            },
        ),
        migrations.CreateModel(
            name='Comments_aya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50, verbose_name='فرستنده')),
                ('text', models.CharField(max_length=50, verbose_name='نظر')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('likeno', models.IntegerField(default=0)),
                ('aya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quran.aya')),
            ],
        ),
    ]
