# Generated by Django 4.0.1 on 2022-01-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joz', models.CharField(max_length=50, verbose_name='انتخاب جز')),
                ('aye', models.CharField(max_length=50, verbose_name='انتخاب آیه')),
                ('soure', models.CharField(max_length=50, verbose_name='انتخاب سوره')),
                ('title', models.CharField(max_length=500, verbose_name='آیه')),
                ('description', models.TextField(max_length=1500, verbose_name='معنی')),
                ('location', models.CharField(max_length=50, verbose_name='سوره و آیه')),
            ],
        ),
        migrations.CreateModel(
            name='Hadis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joz', models.CharField(max_length=50, verbose_name='انتخاب امام')),
                ('aye', models.CharField(max_length=50, verbose_name='انتخاب موضوع')),
                ('soure', models.CharField(max_length=50, verbose_name='انتخاب')),
                ('title', models.CharField(max_length=500, verbose_name='حدیث')),
                ('description', models.TextField(max_length=1500, verbose_name='معنی')),
                ('location', models.CharField(max_length=50, verbose_name='کتاب و صفحه')),
            ],
        ),
    ]
