# Generated by Django 4.0.1 on 2022-01-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_main',
            name='header_logo',
            field=models.ImageField(upload_to='header-logo/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='settings_main',
            name='header_photo',
            field=models.ImageField(upload_to='header_photo', verbose_name='تصویر'),
        ),
    ]
