# Generated by Django 4.0.1 on 2022-01-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aya',
            name='language1',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='ترجمه'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='language2',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='ترجمه'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='language3',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='ترجمه'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='language4',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='ترجمه'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مکان نزول'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='relatedAya',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='آیات مرتبط'),
        ),
        migrations.AlterField(
            model_name='aya',
            name='tafsir',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='تفسیر'),
        ),
    ]
